# Repo-specific hlint rules go here:
- ignore: { name: Use camelCase }

# Relude's .hlint.yaml goes here:
# https://github.com/kowainik/relude/blob/main/.hlint.yaml
- arguments:
    - "-XConstraintKinds"
    - "-XDeriveGeneric"
    - "-XGeneralizedNewtypeDeriving"
    - "-XLambdaCase"
    - "-XOverloadedStrings"
    - "-XRecordWildCards"
    - "-XScopedTypeVariables"
    - "-XStandaloneDeriving"
    - "-XTupleSections"
    - "-XTypeApplications"
    - "-XViewPatterns"
- ignore:
    name: Use head
- ignore:
    name: Use Foldable.forM_
